### ISSUE TITLE
White screen when saving group

### ISSUE THREAD

**Issue by nobodyshome** [TerranUlm/MyBB-Plugin-Teamspeak3-Sync#14] opened 2018-04-04 01:42 UTC
When saving a group no matter if the Teamspeak fields are being edited it goes to a white screen. I can confirm the server connects to Teamspeak. Along with no errors showing up in the "teamspeak3_log.php" file. 

Only thing i could find relating to the issue is this in the Apache error.log file:
`[Wed Apr 04 00:56:16.281549 2018] [:error] [pid 1982] [client -IP and Port was here-] PHP Fatal error:  Uncaught TeamSpeak3_Adapter_ServerQuery_Exception: insufficient client permissions (failed on clientdblist 29/0x1D) in /var/www/forum/TeamSpeak3/Adapter/ServerQuery/Reply.php:319
Stack trace:
#0 /var/www/forum/TeamSpeak3/Adapter/ServerQuery/Reply.php(91): TeamSpeak3_Adapter_ServerQuery_Reply->fetchError(Object(TeamSpeak3_Helper_String))
#1 /var/www/forum/TeamSpeak3/Adapter/ServerQuery.php(141): TeamSpeak3_Adapter_ServerQuery_Reply->__construct(Array, 'clientdblist -c...', Object(TeamSpeak3_Node_Host), true)
#2 /var/www/forum/TeamSpeak3/Node/Abstract.php(73): TeamSpeak3_Adapter_ServerQuery->request('clientdblist -c...', true)
#3 /var/www/forum/TeamSpeak3/Node/Server.php(90): TeamSpeak3_Node_Abstract->request('clientdblist -c...', true)
#4 /var/www/forum/TeamSpeak3/Node/Abstract.php(97): TeamSpeak3_Node_Server->request('clientdblist -c...')
#5 /var/www/forum/TeamSpeak3/Node/Server.php(685): TeamSpeak3_Node_Abstract->execute('clientdblist -c...', Array)
#6 /var/www/forum/inc/plugins/teamspeak3.php(389): TeamSpea in /var/www/forum/TeamSpeak3/Adapter/ServerQuery/Reply.php on line 319`

Any help would be appreciated.

**Comment by TerranUlm** [comment] 2018-04-04 06:42
If you read the error message carefully you can see that your TS query account has "insufficient client permissions". See the Readme for how to configure the permissions.

**Comment by nobodyshome** [comment] 2018-04-04 08:55
I checked that, double checked all the permissions are set correctly too. Unless something in the image is wrong, I'm not sure why the error is displaying insufficient permissions. https://i.imgur.com/Q4H0TQH.png

Also wouldn't explain why the group editor is white screening and never applying the group id to the group?

**Comment by TerranUlm** [comment] 2018-04-04 10:21
You get the white screen due to the PHP error caused by the TS3 library being unable to perform the requested action due to lack of permission. 

Now the question is WHY you get that error?
The permission in your image are exactly the same as I have configured for my own TS. But is that group actually assigned to the account you're using? You can check that in YaTQA but I have to guess the english name for it. In the "Permissions" tab you should see something like "Permissions Overview". Just select any channel and the sync account then press the "eye" button next to it.

But let's get to the missing permission itself. The errormessage is "insufficient client permissions (failed on clientdblist 29/0x1D)". The important part is "29" which is the number of the permission. To get the name of the permission we need to lookup the number somewhere, e.g. here: https://www.tsviewer.com/index.php?page=faq&id=12
The name of permission 29 is b_virtualserver_client_dblist

Checking back with your image, the group has this specific permission assigned, so you should be fine - unless the account isn't actually assigned to that group.

**Comment by nobodyshome** [comment] 2018-04-04 11:08
So these are the settings used for the connection, https://i.imgur.com/9ZlTv1V.png

The IP and Ports work as I can see the Query connecting from the correct IP.

**Comment by TerranUlm** [comment] 2018-04-04 11:18
Did you check the TS Account "MyBB"? Is that account assigned to the servergroup "MyBB"? During connection (or in the TS logs) you should see the user "MyBB" connected to your TS server.

**Comment by nobodyshome** [comment] 2018-04-04 11:24
So the MyBB is the server query group, the same group pictures in the first screenshot. 

MyBB doesn't connect, the only thing that connects is the server query as such:
`<01:56:42> "Unknown from IP:48408" dropped (connection lost)
<01:56:54> "Unknown from IP:48410" connected to channel "[cspacer]Landing Zone"`

Following the tutorial, the only mention of server groups is for:
TeamSpeak 3 Server Guest Channel Group ID which is already set
and
TeamSpeak 3 Server Group ID which I can't save because of it white screening.

I'm probably missing something super stupid here, aren't I?

**Comment by TerranUlm** [comment] 2018-04-04 11:52
You need a TS **user** (and a group) as stated in the instructions:

"You need to create a serverquery **account** - dont use the superadmin account for that! I'll recommend YaTQA (http://yat.qa/) as a TS3 admin tool. The account needs only an limited set of permissions (I've put them in a Query **Group** and added the user to that group):"

That user needs a password so it can login using the API.

**Comment by nobodyshome** [comment] 2018-04-04 12:01
I may be misreading it, but that doesn't define what user needs to be added to what group? 

If its the Server Query Group (in this case MyBB), what user is meant to be added to it?

**Comment by TerranUlm** [comment] 2018-04-04 12:32
Just create a new user in the TS client:

1. create a new identity in the TS client ("Extras"->"Identities"), name it "ServerQuery"
1. create a new favorite for your server, pick a nickname (e.g. "MyBB-Sync") and select "ServerQuery" as the identity
1. connect to your server using that favorite (which actually creates the account)
1. using YaTQA assign that account to the "MyBB" group
1. you might have to reconnect to the server with the new favorite
1. in the TS client open the menu "Tools"->"ServerQuery Login". That opens up a new window where you can select a username and a password for that account. Those are the values you need to put in the plugin settings.

**Comment by nobodyshome** [comment] 2018-04-04 12:49
Works.......thanks for all the help. 

Was wondering if there's a possibility of it going both ways? Assigning a group on TeamSpeak also assigns it to the forums?

**Comment by TerranUlm** [comment] 2018-04-04 12:53
I'm glad I could help!

Going the other way could be done but that's not the purpose of that plugin 😉

**Comment by TerranUlm** [comment] 2019-07-17 11:08
no further update received @nobodyshome so I'm closing the issue.

**Closed as completed by TerranUlm** 2019-07-17 11:08 UTC
